import { ChakraProvider } from "@chakra-ui/react";
import { DM_Sans } from "@next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../../lib/registry";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <StyledComponentsRegistry>
          <ChakraProvider>{children}</ChakraProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
